# Copyright © 2009 Fazlul Shahriar <fshahriar@gmail.com>.
# See LICENSE file for license details.

include $(GOROOT)/src/Make.$(GOARCH)

TARG=status
GOFILES=\
	status.go\

include $(GOROOT)/src/Make.cmd
