# Copyright 2009 The GoMPD Authors. All rights reserved.
# Use of this source code is governed by the MIT
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=gompd.googlecode.com/hg/mpd
GOFILES=\
	client.go\

include $(GOROOT)/src/Make.pkg
